producers:
  - id: r0001
    consumerid: d0001
    consumer_list:
      - consumerA:
          name: 'd0001-dev-logs'
          routing_period: 30
          start_date: '2025-05-07'
          contacts:
            - 'user1@example.com'
      - consumerB:
          name: 'd0001-prod-metrics'
          routing_period: 90
          start_date: '2025-03-01'
          contacts:
            - 'user2@example.com'
  - id: r0002
    consumerid: d0002
    consumer_list:
      - consumerC:
          name: 'd0002-test-traces'
          routing_period: 180
          start_date: '2025-04-28'
          contacts:
            - 'user2@example.com'
